// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TK2-00_Data","status":true,"description":"","parameters":{}},
{"name":"===============","status":false,"description":"|          |          |          |          |          |华丽的分割线|          |          |          |          |          |","parameters":{}},
{"name":"jquery-3","status":true,"description":"","parameters":{}},
{"name":"functions","status":true,"description":"","parameters":{}},
{"name":"localforage","status":true,"description":"","parameters":{}},
{"name":"002-AXY_Toast","status":true,"description":"V1.07 AXY提示消息机制 支持android Toast的许多参数。","parameters":{"X":"10","Y":"10","Width":"300","margin":"10","padding":"4","backgroundcolor":"rgba(0,0,0,0.7)","opacity":"1","TextColor":"yellow","TextShadowColor":"rgba(0,0,0,1)","TextShadowWidth":"1","fontsize":"18","timeout":"3000","fade":"slow","zIndex":"50000","DisplayGainGold":"true","DisplayGainItem":"true","DisplayChangeExp":"true","DisplayLevelUp":"true","DisplayLevelDown":"true","PositivePrefixText":"Got","NegativePrefixText":"Lost","CustomTipsTemplate":"{$prefixtext}<span style=\"color:white\">{$amount}</span>个<span style=\"color:#00FF00\">{$name}</span>"}},
{"name":"===============","status":false,"description":"|          |          |          |          |          |华丽的分割线|          |          |          |          |          |","parameters":{}},
{"name":"003-Event Names","status":true,"description":"| 本地 | 允许事件来显示他们上面的名字。","parameters":{"默认范围":"5","字体大小":"24","Fade":"True","Fade Timer":"30"}},
{"name":"004-ScreenResolution","status":false,"description":"v1.00 屏幕分辨率","parameters":{"Screen Width":"640","Screen Height":"400"}},
{"name":"===============","status":false,"description":"|          |          |          |          |          |华丽的分割线|          |          |          |          |          |","parameters":{}},
{"name":"TK2-06_AXY_AjaxNetStuff","status":false,"description":"v1.69 这个插件通过ajax网络支持rmmv.(本土化修改)","parameters":{"LoadEnable":"true","AppID":"371","URL":"https://shanghai.666rpg.com:6443/game/detail/id/371"}},
{"name":"===============","status":false,"description":"|          |          |          |          |          |华丽的分割线|          |          |          |          |          |","parameters":{}},
{"name":"TK2-00_Plugins","status":true,"description":"v1.00 安卓适配 插件","parameters":{}},
{"name":"TK2-01_Modify","status":true,"description":"|          | 太阁2 调整","parameters":{}},
{"name":"TK2-02_SceneWindow","status":true,"description":"|          | v1.02 自制窗口","parameters":{}},
{"name":"TK2-03_Campaign","status":true,"description":"|          | v1.02 自制剧本系统","parameters":{"EnableCancelB":"true"}},
{"name":"TK2-04_System","status":true,"description":"","parameters":{}}
];
